### ISSUE TITLE
Possible state with no result

### ISSUE THREAD

**Issue by kubasienki** [Expurple/smawg#1]
I've been trying to make an RL bot for the game and it found an inescapable state. 

When you try to use dice and all of your tokens, but have no own regions, and lose then you'll be stuck in a state _USED_DICE.
With no option to close the round as you have tokens on hand and no regions to deploy them to

**Comment by Expurple** [comment]
Thanks for reporting, I'll investigate this

**Comment by Expurple** [comment]
The game rules kinda assume that this never happens and the player always has some regions before using the dice:

> If the sum of the die rolled, combined with the Race token(s)
left in his possession, is high enough to conquer the Region, the
player deploys his remaining Race token(s) there. Otherwise, he
deploys his remaining token(s) in one of the Regions he already
occupied prior. Either way, his conquests for the turn end
immediately thereafter.

I've removed the deploy requirement in this situation. Now you should be able to close the round
